set system host-name edge-fw01

set interfaces irb unit 50 description GUESTS
set interfaces irb unit 50 family inet address 10.50.50.1/24

set interfaces irb unit 60 description WIFI
set interfaces irb unit 60 family inet address 10.60.60.1/24